[start]
cmd = "npx tsx src/server.ts"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "mkdir -p public/dist",
  "cd frontend && npm run build",
  "ls -la public/dist"
]
